port python logic -> bash script

diff --git a/bin/tmux-run b/bin/tmux-run
--- a/bin/tmux-run
+++ b/bin/tmux-run
@@ -1,62 +1,97 @@
 #!/usr/bin/env bash
 
+usage="usage: tmux-run <session-name> \\
+  [-h|--help] \\
+  [[-l|--layout=]{number}] \\              # [default: generated to match number of commands provided] each digit represents number of panes in column
+  [[-o|--orientation=]ttb|ltr] \\          # [default: ttb (top-to-bottom)] transpose layout if orientation=ltr (left-to-right)
+  [[-e|--exists=]replace|attach|error] \\  # [default: replace] exists when session already exists
+  [--extra=\"tmux cmd a ; tmux cmd b\"] \\   # extra tmux commands to be executed after window and panes are created
+  [\"shell command 1\"] \\                   # shell commands that will be executed in each pane
+  [\"shell command 2\"] \\
+  ...
+  [\"shell command N\"] \\                   # number of shell commands N must not exceed sum of layout
+"
+
+# --help
+if [[ $1 =~ ^(--help|-h)$ ]]; then
+  echo "$usage"
+  exit 0
+fi
+
 # parse args into vars:
 session=""      # required - session name
-behavior=""     # optional - attach/replace/error behavior when session already exists
-layout=""       # optional - string of digits defining a custom layout - each digit represents num of panes in each column
-orientation=""  # optional - "ttb" (top-to-bottom, default) or "ltr" (left-to-right). If "ltr", transpose layout into rows instead of columns
-options=""      # optional - extra tmux window options that will be set for the session
+layout=""       # optional - string of digits defining a custom layout
+                #            each digit represents num of panes in each column
+orientation=""  # optional - ttb (top-to-bottom, default) or ltr (left-to-right)
+                #            if ltr, transpose layout into rows instead of columns
+exists=""       # optional - attach/replace/error exists when session exists
+extra=""        # optional - extra commands to be executed after layout commands
+                #            e.g. extra="set-window-option remain-on-exit off"
 
 # 1st arg: session name
 session="$1"
 shift
 
-# 2nd arg: behavior [replace-existing|attach-existing|error-existing] default:replace-existing
-behavior=$(echo "$1" | awk '{print tolower($0)}')
-if [[ $behavior = "replace-existing" ]]; then
-  shift
-elif [[ $behavior = "attach-existing" ]]; then
-  shift
-elif [[ $behavior = "error-existing" ]]; then
-  shift
-else
-  # default
-  behavior="replace-existing"
-fi
-echo $behavior
-
-# 3rd arg: layout (string of digits)
-if [[ $1 =~ ^[0-9]+$ ]]; then
+# 2nd arg: layout (string of digits)
+if [[ $1 =~ ^--layout= ]] || [[ $1 =~ ^(--layout=|-l)?[0-9]+$ ]]; then
   layout="$1"
   shift
-
+  layout="${layout#"--layout="}"  # remove prefix (if necessary)
+  layout="${layout#"-l"}"
+  # if layout invalid, exit with error
+  if ! [[ $layout =~ ^[0-9]+$ ]]; then
+    echo "invalid input: --layout=$layout cannot contain non-numeric characters"
+    echo "$usage"
+    exit 1
+  fi
   # if layout contains zero, exit with error
-  if [[ $layout =~ "0" ]]; then
-    echo "layout column cannot be set to zero"
+  if [[ $layout =~ 0 ]]; then
+    echo "invalid input: --layout=$layout column cannot be set to zero"
+    echo "$usage"
     exit 1
   fi
 fi
 
-# 4th arg: orientation [ltr|ttb] default:ttb
+# 3rd arg: orientation [ltr|ttb] default:ttb
 orientation=$(echo "$1" | awk '{print tolower($0)}')
-if [[ $orientation = "ltr" ]]; then
+if [[ $1 =~ ^--orientation= ]] || [[ $1 =~ ^(--orientation=|-o)?(ttb|ltr)$ ]]; then
+  orientation="$1"
   shift
-elif [[ $orientation = "ttb" ]]; then
-  shift
-else
+  orientation="${orientation#"--orientation="}"  # remove prefix (if necessary)
+  orientation="${orientation#"-o"}"
+  if ! [[ $orientation =~ ^(ttb|ltr)$ ]]; then
+    echo "invalid input: --orientation must be [ttb|ltr]"
+    echo "$usage"
+    exit 1
+  fi
+fi
+if [[ -z $orientation ]]; then
   # default
   orientation="ttb"
 fi
 
-# 5th arg: options (json string)
-if jq -e . >/dev/null 2>&1 <<< "$1"; then
-  options="$1"
+# 4th arg: exists [replace|attach|error] default:replace
+if [[ $1 =~ ^--exists= ]] || [[ $1 =~ ^(--exists=|-e)?(replace|attach|error)$ ]]; then
+  exists="$1"
   shift
-else
+  exists="${exists#"--exists="}"  # remove prefix (if necessary)
+  exists="${exists#"-e"}"
+  if ! [[ $exists =~ ^(replace|attach|error)$ ]]; then
+    echo "invalid input: --exists must be [replace|attach|error]"
+    echo "$usage"
+    exit 1
+  fi
+fi
+if [[ -z $exists ]]; then
   # default
-  options='{
-    "remain-on-exit": "on"
-  }'
+  exists="replace"
+fi
+
+# 5th arg: extra
+if [[ $1 =~ ^--extra= ]]; then
+  extra="$1"
+  shift
+  extra="${extra#"--extra="}"  # remove prefix
 fi
 
 numcmds="$#"
@@ -72,12 +107,12 @@ numcmds="$#"
 # numcmds:8 -> layout:"233"
 # ...
 if [[ -z $layout ]]; then
-  root=$(bc <<< "scale=0; sqrt($numcmds+1)")
+  root=$( bc <<< "scale=0; sqrt($numcmds+1)" )
   root=${root%.*}  # floor
-  quot=$(($numcmds / $root))
+  quot=$(( $numcmds / $root ))
   quot=${quot%.*}  # floor
-  rmdr=$(($numcmds % $root))
-  layout=$(printf "%0.s$root" $(seq 1 $quot))
+  rmdr=$(( $numcmds % $root ))
+  layout=$( printf "%0.s$root" $( seq 1 $quot ) )
   if (( $rmdr > 0 )); then
     layout="$rmdr$layout"
   fi
@@ -87,19 +122,78 @@ fi
 layoutsum=0
 for (( i = 0; i < ${#layout}; i++ )); do (( layoutsum += ${layout:i:1} )); done
 if (( $numcmds > $layoutsum )); then
-  echo "layout is too small for number of commands provided"
+  echo "invalid input: --layout=$layout is too small for number of commands provided"
+  echo "$usage"
   exit 1
 fi
 
-if [[ $behavior = "attach-existing" ]]; then
+if [[ $exists == "attach" ]]; then
   tmux has-session -t $session 2>/dev/null
   if [ $? == 0 ]; then  # if session exists, re-attach
     tmux attach-session -t $session
     exit 0
   fi
-elif [[ $behavior = "replace-existing" ]]; then
+elif [[ $exists == "replace" ]]; then
   tmux kill-session -t "$session" || true  # ignore 'session does not exist' error
 fi
 
-dir="$(dirname "$(readlink "$0")")"  # ensure dir refers to original script not symlink
-eval $($dir/../layout.py "$session" "$options" "$layout" "$orientation" "$@")
+cmds=("$@")
+tmuxcmd="tmux new-session -s \"$session\" \"${cmds[0]}\""
+
+splitpane () {
+  local direction="$1"
+  shift
+  local numpanes="$1"
+  shift
+  local cmds=( "$@" )
+
+  if (( $numpanes >= 2 )); then
+    if (( $numpanes == 2 )); then
+      tmuxcmd+=" \\; split-window -$direction \"${cmds[1]}\""
+    elif (( $numpanes % 2 > 0 )); then
+      # percentage = round(100 - (100 / $numpanes))
+      local percentage=$(( 100 - ( ( 100 + ( $numpanes / 2 ) ) / $numpanes ) ))
+      tmuxcmd+=" \\; split-window -$direction -p$percentage \"${cmds[1]}\""
+      splitpane $direction $(( $numpanes - 1 )) "${cmds[@]:1}"
+    else
+      local half=$(( $numpanes / 2 ))
+      tmuxcmd+=" \\; split-window -$direction -d \"${cmds[$half]}\""
+      splitpane $direction $half "${cmds[@]:0:half}"  # 1st half of commands
+      [[ $direction == "v" ]] && flag="D" || flag="R"
+      tmuxcmd+=" \\; select-pane -$flag"
+      splitpane $direction $half "${cmds[@]:half}"    # 2nd half of commands
+    fi
+  fi
+}
+
+# construct initial set of column panes (or row panes if orientation="ltr")
+topcmds=()
+colsum=0
+numcols=${#layout}
+for (( i = 0; i < $numcols; i++ )); do
+  col=${layout:i:1}
+  topcmds+=( "${cmds[$colsum]}" )
+  (( colsum+=$col ))
+done
+[[ $orientation == "ltr" ]] && direction="v" || direction="h"
+splitpane $direction $numcols "${topcmds[@]}"
+
+# select first column pane (or row pane if orientation="ltr")
+tmuxcmd+=" \\; select-pane -t0"
+
+# split each column pane as specified by layout (or row panes if orientation="ltr")
+colsum=0
+for (( i = 0; i < ${#layout}; i++ )); do
+  col=${layout:i:1}
+  [[ $orientation == "ltr" ]] && direction="h" || direction="v"
+  splitpane $direction $col "${cmds[@]:$colsum:col}"
+  [[ $orientation == "ltr" ]] && flag="D" || flag="R"
+  tmuxcmd+=" \\; select-pane -$flag"
+  (( colsum+=$col ))
+done
+
+# append extra tmux commands as specified by `extra` arg
+tmuxcmd+=" \\; set-window-option remain-on-exit on"
+tmuxcmd+=" \\; ${extra//;/\\\\;}"  # escape semicolons - replace ";" with "\\;"
+
+eval $tmuxcmd
