nested layouts

diff --git a/tmux-run b/tmux-run
--- a/tmux-run
+++ b/tmux-run
@@ -14,16 +14,16 @@ usage='usage: tmux-run <session-name> \          # session name required unless 
 '
 
 # parse args into vars:
-session=""      # required - session name
-layout=""       # optional - string of digits defining a custom layout
+argsession=""      # required - session name
+arglayout=""       # optional - string of digits defining a custom layout
                 #            each digit represents num of panes in each column
-orientation=""  # optional - ttb (top-to-bottom, default) or ltr (left-to-right)
+argorientation=""  # optional - ttb (top-to-bottom, default) or ltr (left-to-right)
                 #            if ltr, transpose layout into rows instead of columns
-exists=""       # optional - attach/replace/error exists when session exists
-extra=""        # optional - extra commands to be executed after layout commands
+argexists=""       # optional - attach/replace/error exists when session exists
+argextra=""        # optional - extra commands to be executed after layout commands
                 #            e.g. extra="set-window-option remain-on-exit off"
-npm=""          # optional - if set, prefix each command with "npm run" for package.json scripts
-cmds=""         # optional - list of commands to be executed in resulting panes
+argnpm=""          # optional - if set, prefix each command with "npm run" for package.json scripts
+argcmds=""         # optional - list of commands to be executed in resulting panes
 
 # tmux command that will be constructed and executed:
 tmuxcmd=""
@@ -36,36 +36,35 @@ function processargs () {
   fi
 
   # 1st arg: session name
-  session="$1"
+  argsession="$1"
   shift
 
   # 2nd arg: npm
-  if [[ "$session" =~ ^(--npm|-n)$ ]]; then
+  if [[ "${argsession}" =~ ^(--npm|-n)$ ]]; then
     # allow ommission of session name if --npm is set
-    npm="true"
-    session="$npm_package_name"
+    argnpm="true"
+    argsession="$npm_package_name"
   elif [[ "$1" =~ ^(--npm|-n)$ ]]; then
-    npm="true"
+    argnpm="true"
     shift
   fi
 
   # 3rd arg: layout (string of digits)
-  if [[ "$1" =~ ^--layout= ]] || [[ "$1" =~ ^(--layout|-l)?=?[0-9]+$ ]]; then
+  if [[ "$1" =~ ^--layout= ]] || [[ "$1" =~ ^(--layout|-l)?=?[][0-9]+$ ]]; then
+    arglayout="$1"
     shift
-    layout="$1"
-    shift
-    layout="${layout#--layout}"  # remove prefix (if necessary)
-    layout="${layout#-l}"
-    layout="${layout#=}"
+    arglayout="${arglayout#--layout}"  # remove prefix (if necessary)
+    arglayout="${arglayout#-l}"
+    arglayout="${arglayout#=}"
     # if layout invalid, exit with error
-    if ! [[ "${layout}" =~ ^[0-9]+$ ]]; then
-      echo "invalid input: --layout=${layout} cannot contain non-numeric characters"
+    if ! [[ "${arglayout}" =~ ^[][0-9]+$ ]]; then
+      echo "invalid input: --layout=${arglayout} must contain only numeric characters and brackets"
       echo "${usage}"
       exit 1
     fi
     # if layout contains zero, exit with error
-    if [[ "${layout}" =~ 0 ]]; then
-      echo "invalid input: --layout=${layout} column cannot be set to zero"
+    if [[ "${arglayout}" =~ 0 ]]; then
+      echo "invalid input: --layout=${arglayout} column cannot be set to zero"
       echo "${usage}"
       exit 1
     fi
@@ -73,47 +72,47 @@ function processargs () {
 
   # 4th arg: orientation [ltr|ttb] default:ttb
   if [[ "$1" =~ ^--orientation= ]] || [[ "$1" =~ ^(--orientation|-o)?=?(ttb|ltr)$ ]]; then
-    orientation="$1"
+    argorientation="$1"
     shift
-    orientation="${orientation#--orientation}"  # remove prefix (if necessary)
-    orientation="${orientation#-o}"
-    orientation="${orientation#=}"
-    if ! [[ $orientation =~ ^(ttb|ltr)$ ]]; then
-      echo "invalid input: --orientation=${orientation} must be [ttb|ltr]"
-      echo "$usage"
+    argorientation="${argorientation#--orientation}"  # remove prefix (if necessary)
+    argorientation="${argorientation#-o}"
+    argorientation="${argorientation#=}"
+    if ! [[ "${argorientation}" =~ ^(ttb|ltr)$ ]]; then
+      echo "invalid input: --orientation=${argorientation} must be [ttb|ltr]"
+      echo "${usage}"
       exit 1
     fi
   else
     # default
-    orientation="ttb"
+    argorientation="ttb"
   fi
 
   # 5th arg: exists [replace|attach|error] default:replace
   if [[ "$1" =~ ^--exists= ]] || [[ "$1" =~ ^(--exists|-e)?=?(replace|attach|error)$ ]]; then
-    exists="$1"
+    argexists="$1"
     shift
-    exists="${exists#--exists}"  # remove prefix (if necessary)
-    exists="${exists#-e}"
-    exists="${exists#=}"
-    if ! [[ $exists =~ ^(replace|attach|error)$ ]]; then
-      echo "invalid input: --exists=${exists} must be [replace|attach|error]"
-      echo "$usage"
+    argexists="${argexists#--exists}"  # remove prefix (if necessary)
+    argexists="${argexists#-e}"
+    argexists="${argexists#=}"
+    if ! [[ "${argexists}" =~ ^(replace|attach|error)$ ]]; then
+      echo "invalid input: --exists=${argexists} must be [replace|attach|error]"
+      echo "${usage}"
       exit 1
     fi
   else
     # default
-    exists="replace"
+    argexists="replace"
   fi
 
   # 6th arg: extra
   if [[ "$1" =~ ^--extra=? ]]; then
-    extra="$1"
+    argextra="$1"
     shift
-    extra="${extra#--extra}"  # remove prefix
-    extra="${extra#=}"
+    argextra="${argextra#--extra}"  # remove prefix
+    argextra="${argextra#=}"
   fi
 
-  cmds=( "$@" )
+  argcmds=( "$@" )
 }
 
 function generatelayout () {
@@ -132,24 +131,25 @@ function generatelayout () {
   # $1 size [integer] size of layout
 
   # modifies:
-  # ${layout}
+  # ${arglayout}
 
   local size
-  local root
-  local quot
-  local rmdr
 
   size="$1"
   shift
+
+  local root
+  local quot
+  local rmdr
 
   root=$( bc <<< "scale=0; sqrt( ${size} + 1 )" )
   root=${root%.*}  # floor
   quot=$(( ${size} / ${root} ))
   quot=${quot%.*}  # floor
   rmdr=$(( ${size} % ${root} ))
-  layout=$( printf "%0.s${root}" $( seq 1 "${quot}" ) )
+  arglayout=$( printf "%0.s${root}" $( seq 1 "${quot}" ) )
   if (( "${rmdr}" > 0 )); then
-    layout="${rmdr}${layout}"
+    arglayout="${rmdr}${arglayout}"
   fi
 }
 
@@ -157,25 +157,70 @@ function validatelayout () {
   # ensure layout is large enough to contain specified size
 
   # params:
-  # $1 size [integer] minimum size of layout
+  # $1 minsize [integer] minimum size of layout
 
-  local size
-  local layoutsum
+  local minsize
 
-  size="$1"
+  minsize="$1"
   shift
 
+  local idx
+  local char
+  local layoutsizesum
+
+  layoutsizesum=0
+  for (( idx = 0; "${idx}" < "${#arglayout}"; idx++ )); do
+    char="${arglayout:${idx}:1}"
+    if [[ "${char}" =~ [0-9] ]]; then
+      (( layoutsizesum+="${char}" ))
+    fi
+  done
+
   # if size exceeds sum of layout string digits, exit with error
-  layoutsum=0
-  for (( i = 0; i < "${#layout}"; i++ )); do (( layoutsum+="${layout:i:1}" )); done
-  if (( "${size}" > "${layoutsum}" )); then
-    echo "invalid input: --layout=${layout} is too small for number of commands provided"
+  if (( "${minsize}" > "${layoutsizesum}" )); then
+    echo "invalid input: --layout=${arglayout} is too small for number of commands provided"
     echo "${usage}"
     exit 1
   fi
 }
 
-function splitpane () {
+function selectpane () {
+  # construct a set of tmux select-pane commands according to params
+
+  # params:
+  # $1 direction [string "v"|"h"]    direction to split current pane (vertical or horizontal)
+  # $2 flags     [string]            pair of flags that will be used based on direction
+  # $3 repeat    [integer default=1] number of times the select-pane operation will be repeated
+
+  # modifies:
+  # ${tmuxcmd}
+
+  local direction
+  local flags
+  local repeat
+
+  direction="$1"
+  shift
+  flags="$1"
+  shift
+  repeat="$1"
+  shift
+
+  local idx
+  local flag
+
+  if [[ -z "${repeat}" ]]; then
+    repeat=1
+  fi
+
+  [[ "${direction}" == "v" ]] && flag="${flags:0:1}" || flag="${flags:1:1}"
+
+  for (( idx = 0; "${idx}" < "${repeat}"; idx++ )); do
+    tmuxcmd+=" \\; select-pane -${flag}"
+  done
+}
+
+function split1d () {
   # construct a set of tmux split-window and select-pane commands that will split
   # the current pane into `numpanes` equally-sized separate panes
 
@@ -190,15 +235,16 @@ function splitpane () {
   local direction
   local numpanes
   local cmds
-  local percentage
-  local half
-  local flag
 
   direction="$1"
   shift
   numpanes="$1"
   shift
   cmds=( "$@" )
+
+  local percentage
+  local half
+  local flag
 
   if (( "${numpanes}" >= 2 )); then
     if (( "${numpanes}" == 2 )); then
@@ -207,66 +253,124 @@ function splitpane () {
       # percentage = round(100 - (100 / $numpanes))
       percentage=$(( 100 - ( ( 100 + ( ${numpanes} / 2 ) ) / ${numpanes} ) ))
       tmuxcmd+=" \\; split-window -${direction} -p${percentage} \"${cmds[1]}\""
-      splitpane "${direction}" "$(( ${numpanes} - 1 ))" "${cmds[@]:1}"
+      split1d "${direction}" "$(( ${numpanes} - 1 ))" "${cmds[@]:1}"
     else
       half=$(( ${numpanes} / 2 ))
       tmuxcmd+=" \\; split-window -$direction -d \"${cmds[${half}]}\""
-      splitpane "${direction}" "${half}" "${cmds[@]:0:${half}}"  # 1st half of cmds
-      [[ "${direction}" == "v" ]] && flag="D" || flag="R"
-      tmuxcmd+=" \\; select-pane -${flag}"
-      splitpane "${direction}" "${half}" "${cmds[@]:${half}}"    # 2nd half of cmds
+      split1d "${direction}" "${half}" "${cmds[@]:0:${half}}"  # 1st half of cmds
+      selectpane "${direction}" "DR"
+      split1d "${direction}" "${half}" "${cmds[@]:${half}}"    # 2nd half of cmds
     fi
   fi
 }
 
-function splitwindow () {
+function split2d () {
   # construct a set of tmux split-window and select-pane commands that will split
-  # the current window into `numpanes` equally-sized separate panes according to layout
+  # the current pane according to layout
 
   # params:
-  # $@ cmds [array<string>] list of commands to be executed in resulting panes
-
-  # references:
-  # ${layout}
-  # ${orientation}
+  # $1 direction [string "v"|"h"] direction to split current pane (vertical or horizontal)
+  # $2 layout    [string]         number of panes to split current pane into
+  # $@ cmds      [array<string>]  list of commands to be executed in resulting panes
 
   # modifies:
   # ${tmuxcmd}
 
-  local cmds
-  local topcmds
-  local col
-  local colsum
-  local numcols
   local direction
-  local flag
+  local layout
+  local cmds
 
+  direction="$1"
+  shift
+  layout="$1"
+  shift
   cmds=( "$@" )
 
-  # construct initial set of column panes (or row panes if orientation="ltr")
-  topcmds=()
-  colsum=0
-  numcols="${#layout}"
-  for (( i = 0; i < "${numcols}"; i++ )); do
-    col=${layout:${i}:1}
-    topcmds+=( "${cmds[${colsum}]}" )
-    (( colsum+=$col ))
+  local idx
+  local char
+  local depth
+  local flag
+
+  local sublayouts
+  local numsublayouts
+  local sublayoutsizes
+  local sublayoutsize
+
+  local initialcmds
+  local initialcmdidx
+  local subcmds
+
+  # expand layout string into two arrays: sublayouts & sublayoutsizes
+  # e.g. "12[34[5]]6" -> ["1", "11", "34[5]", "111111"]  # sublayouts
+  #                   -> [ 1,   2,    12,      6      ]  # sublayoutsizes
+  depth=0
+  sublayouts=()
+  sublayoutsizes=()
+  for (( idx = 0; "${idx}" < "${#layout}"; idx++ )); do
+    char="${layout:${idx}:1}"
+
+    if [[ "${char}" == "]" ]]; then
+      (( depth-=1 ))
+    fi
+
+    if (( "${depth}" > 0 )); then
+      sublayouts[$(( ${#sublayouts[@]} - 1 ))]+="${char}"
+
+      if [[ "${char}" =~ [0-9] ]]; then
+        (( sublayoutsizes[$(( ${#sublayoutsizes[@]} - 1 ))]+=${char} ))
+      fi
+    fi
+
+    if [[ "${char}" == "[" ]]; then
+      if (( "${depth}" == 0 )); then
+        sublayouts+=( "" )
+        sublayoutsizes+=( 0 )
+      fi
+      (( depth+=1 ))
+    fi
+
+    if [[ "${char}" =~ [0-9] ]] && (( "${depth}" == 0 )); then
+      sublayoutsizes+=( "${char}" )
+      sublayouts+=( $( printf "%0.s1" $( seq 1 "${char}" ) ) )
+    fi
   done
-  [[ "${orientation}" == "ltr" ]] && direction="v" || direction="h"
-  splitpane "${direction}" "${numcols}" "${topcmds[@]}"
 
-  # select first column pane (or row pane if orientation="ltr")
-  tmuxcmd+=" \\; select-pane -t0"
+  numsublayouts="${#sublayouts[@]}"
 
-  # split each column pane as specified by layout (or row panes if orientation="ltr")
-  colsum=0
-  for (( i = 0; i < "${#layout}"; i++ )); do
-    col=${layout:${i}:1}
-    [[ "${orientation}" == "ltr" ]] && direction="h" || direction="v"
-    splitpane "${direction}" "${col}" "${cmds[@]:${colsum}:${col}}"
-    [[ "${orientation}" == "ltr" ]] && flag="D" || flag="R"
-    tmuxcmd+=" \\; select-pane -$flag"
-    (( colsum+=${col} ))
+  # construct initial set of panes
+  initialcmds=()
+  initialcmdidx=0
+  for (( i = 0; i < "${numsublayouts}"; i++ )); do
+    sublayoutsize="${sublayoutsizes[${i}]}"
+    initialcmds+=( "${cmds[${initialcmdidx}]}" )
+    (( initialcmdidx+="${sublayoutsize}" ))
+  done
+  split1d "${direction}" "${numsublayouts}" "${initialcmds[@]}"
+
+  # select first pane
+  selectpane "${direction}" "UL" $(( ${numsublayouts} - 1 ))
+
+  # split each pane as specified by layout
+  initialcmdidx=0
+  for (( idx = 0; "${idx}" < "${numsublayouts}"; idx++ )); do
+    sublayout="${sublayouts[${idx}]}"
+    sublayoutsize="${sublayoutsizes[${idx}]}"
+
+    if (( ${idx} > 0 )); then
+      selectpane "${direction}" "DR"
+    fi
+
+    [[ "${direction}" == "v" ]] && flag="h" || flag="v"
+    subcmds=( "${cmds[@]:${initialcmdidx}:${sublayoutsize}}" )
+
+    # if layout contains only columns of 1, we can split 1-dimensional
+    if [[ "${sublayout}" =~ ^1+$ ]]; then
+      split1d "${flag}" "${sublayoutsize}" "${subcmds[@]}"
+    else
+      split2d "${flag}" "${sublayout}" "${subcmds[@]}"
+    fi
+
+    (( initialcmdidx+="${sublayoutsize}" ))
   done
 }
 
@@ -277,34 +381,37 @@ function main () {
   # $@ args [array<any>] arguments passed to script
 
   # references:
-  # ${session}
-  # ${layout}
-  # ${orientation}
-  # ${exists}
-  # ${extra}
-  # ${cmds}
+  # ${argsession}
+  # ${arglayout}
+  # ${argorientation}
+  # ${argexists}
+  # ${argextra}
+  # ${argcmds}
 
   # modifies:
   # ${tmuxcmd}
 
+  local idx
+  local flag
   local numcmds
 
   processargs "$@"
 
-  numcmds="${#cmds[@]}"
+  numcmds="${#argcmds[@]}"
 
   # if npm option is set, prefix commands "npm run ..."
-  if [[ -n "${npm}" ]]; then
-    for (( i = 0; i < "${#cmds[@]}"; i++ )); do
-      cmds[i]="npm run ${cmds[i]}"
+  if [[ -n "${argnpm}" ]]; then
+    for (( idx = 0; "${idx}" < "${#argcmds[@]}"; idx++ )); do
+      argcmds[idx]="npm run ${argcmds[idx]}"
+      #argcmds["${idx}"]="echo \"${argcmds[${idx}]}\" && sleep 1000"
     done
   fi
 
   # begin to construct tmux command
-  tmuxcmd+="tmux new-session -s \"${session}\" \"${cmds[0]}\""
+  tmuxcmd+="tmux new-session -s \"${argsession}\" \"${argcmds[0]}\""
 
   # if layout is not specified, generate a default
-  if [[ -z "${layout}" ]]; then
+  if [[ -z "${arglayout}" ]]; then
     generatelayout "${numcmds}"
   fi
 
@@ -312,25 +419,27 @@ function main () {
   validatelayout "${numcmds}"
 
   # append layout commands onto tmuxcmd
-  splitwindow "${cmds[@]}"
+  [[ "${argorientation}" == "ltr" ]] && flag="v" || flag="h"
+  split2d "${flag}" "${arglayout}" "${argcmds[@]}"
 
   # append extra tmux commands as specified by `extra` arg onto tmuxcmd
   tmuxcmd+=" \\; set-window-option remain-on-exit on"
-  tmuxcmd+=" \\; ${extra//;/\\\\;}"  # escape semicolons - replace ";" with "\\;"
+  tmuxcmd+=" \\; ${argextra//;/\\\\;}"  # escape semicolons - replace ";" with "\\;"
 
   # either attach to an existing session or kill it based on specified behavior
-  if [[ "${exists}" == "attach" ]]; then
-    tmux has-session -t "${session}" 2>/dev/null
+  if [[ "${argexists}" == "attach" ]]; then
+    tmux has-session -t "${argsession}" 2>/dev/null
     if [ "$?" == 0 ]; then  # if session exists, re-attach
-      tmux attach-session -t "${session}"
+      tmux attach-session -t "${argsession}"
       exit 0
     fi
-  elif [[ $exists == "replace" ]]; then
-    tmux kill-session -t "${session}" || true  # ignore 'session does not exist' error
+  elif [[ "${argexists}" == "replace" ]]; then
+    tmux kill-session -t "${argsession}" || true  # ignore 'session does not exist' error
   fi
 
   # execute constructed tmux command
   bash -c "${tmuxcmd}"
+  #echo "${tmuxcmd}"
 }
 
 main "$@"
